name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    
    strategy:
      matrix:
        os:
          - ubuntu
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Install dependencies
      timeout-minutes: 10
      run: npm ci
    
    - name: Compile typescript
      timeout-minutes: 10
      run: npm run compile
    
    - name: Run tests
      timeout-minutes: 10
      run: xvfb-run -a npm test
